server:
  port: 9090

spring:
  devtools:
    restart:
      enabled: false
    livereload:
      enabled: false
  thymeleaf:
    mode: XHTML
    cache: false
database:
  url: jdbc:mysql://localhost:3306/usercenter?useUnicode=true&characterEncoding=UTF-8
  driver: com.mysql.jdbc.Driver
  userName: root
  password: test
template:
  entityPackagePath: com.example.usercenter.sys.entity
  daoPackagePath: com.example.usercenter.sys.dao
  servicePackagePath: com.example.usercenter.sys.service
  controllerPackagePath: com.example.usercenter.sys.web
  baseDao: com.example.usercenter.common.base.BaseDao
  baseService: com.example.usercenter.common.base.BaseService
  baseController: com.example.usercenter.common.base.BaseRestController
  pageResponseClassPath: com.example.usercenter.common.base.Page
  responseResultClassPath: com.example.usercenter.common.base.RespBody